ignore:
  # Exclude the version file from all coverage calculations
  - "src/kodeagent/_version.py"
  - "src/kodeagent/examples.py"

coverage:
  status:
    patch:
      default:
        target: 80%
        threshold: 5%