"""Example agent that reviews state-of-the-art research papers on a given topic and generates
a PowerPoint slide deck presentation summarizing the findings.
Set `PEXEL_API_KEY` environment variable to use images in the slides.
"""

from kodeagent import ReActAgent, print_response
from kodeagent.tools import search_arxiv, tool


@tool
def generate_powerpoint_slide_deck(topic_or_contents: str) -> str:
    """Create a PowerPoint presentation (.pptx file) on the given topic and return the file path.
    `topic_or_contents` can be a short text describing a specific topic. Alternatively, it can
    also be as long as the contents of a file based on which the slide deck is to be generated.
    The path to the generated PowerPoint slide deck generated by this tool should be returned
    to the user.

    Args:
        topic_or_contents: The topic (or detailed contents) for the presentation.

    Returns:
        The file path to the PowerPoint slide deck.
    """
    try:
        from slidedeckai.core import SlideDeckAI
    except ImportError as e:
        raise ImportError(
            'Please install the `slidedeckai` package to use this tool: pip install slidedeckai'
        ) from e

    # Gemini API key is set via env variable
    slide_generator = SlideDeckAI(
        model='[gg]gemini-2.0-flash-lite',  # SlideDeckAI uses a different model naming convention
        topic=topic_or_contents,
    )
    pptx_path = slide_generator.generate()
    print(f'🤖 Generated slide deck: {pptx_path}')

    return pptx_path


async def main():
    """Agent to review SOTA research papers and generate a slide deck presentation."""
    agent = ReActAgent(
        name='SOTA Review Presenter',
        description='Creates a slide deck reviewing the state-of-the-art research on any topic.',
        model_name='gemini/gemini-2.0-flash-lite',  # 'gpt-4.1-mini'
        tools=[search_arxiv, generate_powerpoint_slide_deck],
        max_iterations=5,
    )
    task = (
        'Review six recent papers on AI for healthcare and generate a slide deck summarizing'
        ' the state-of-the-art research. Add a slide to synthesize key trends.'
        ' Add another slide on the future directions. The last slide should list the references.'
        ' Return the slide deck file path.'
    )

    async for response in agent.run(task):
        print_response(response, only_final=True)


if __name__ == '__main__':
    import asyncio

    if hasattr(asyncio, 'WindowsSelectorEventLoopPolicy'):
        asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())

    asyncio.run(main())
